### ISSUE TITLE
starlette-base should have a run_constraint on starlet

### ISSUE THREAD

**Issue by xhochy** [conda-forge/starlette-feedstock#57]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

We see issues like https://github.com/conda-forge/fastapi-feedstock/issues/43 popping up where an old `starlette-base` version is installed alongside a new `starlette` version causing file clobbering and random behaviour which version of `starlette` is actually installed really at the end.

Thus we should add a repodata patch that add a `run_constraint` for `starlette` to `starlette-base`.

**Comment by carlodri** [comment]
Thanks for reporting, and sorry for the mess....`starlette-base` no longer exists, it existed only for versions 0.13.5 and 0.13.6. Packages were then renamed to `starlette` and `starlette-full`. How do you suggest we fix this? We could mark those packages as broken so that the legacy naming disappears, and if those specific versions are required we could make a back-release. What do you think?

**Comment by xhochy** [comment]
I would just patch the repodata.json with the above run_constrained. PR coming from me in the next days.

**Comment by xhochy** [comment]
Made a PR at https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/106
